services:
  - type: web
    name: reserva-pilates-bot
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt && playwright install
    startCommand: python main.py
    envVars:
      - key: EMAIL_GYM
        sync: false
      - key: PASS_GYM
        sync: false
      - key: EMAIL_GYM2
        sync: false
      - key: PASS_GYM2
        sync: false
      - key: EMAIL_GYM3
        sync: false
      - key: PASS_GYM3
        sync: false
      - key: EMAIL_REMITENTE
        sync: false
      - key: EMAIL_REMITENTE2
        sync: false
      - key: EMAIL_REMITENTE3
        sync: false
      - key: EMAIL_DESTINO
        sync: false
      - key: EMAIL_DESTINO2
        sync: false
      - key: EMAIL_DESTINO3
        sync: false
      - key: MJ_APIKEY_PUBLIC
        sync: false
      - key: MJ_APIKEY_PRIVATE
        sync: false
